/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package program;

import control.EI;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import objektumok.Auto;

/**
 *
 * @author Szabó
 */
public class GuiAutosProgram extends javax.swing.JFrame  implements EI.BBListener{
    Auto[] autok;
    int melyikauto;
    /**
     * Creates new form GuiAutosProgram
     */
    public GuiAutosProgram() {
        autok = new Auto[0];
        this.melyikauto = autok.length > 0 ? 0 : -1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlUjAuto = new javax.swing.JPanel();
        Chk_beintitva = new javax.swing.JCheckBox();
        btnResetUezemaDefekt = new javax.swing.JButton();
        btnGarazsba = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Mum_potkerek = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        Chk_defekt = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Mum_uzemanyagszint = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Txt_autoneve = new javax.swing.JTextField();
        pnlGarazs = new javax.swing.JPanel();
        cmbAutok = new javax.swing.JComboBox<>();
        sldEsely = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        chbDefekt = new javax.swing.JCheckBox();
        btnMegy = new javax.swing.JButton();
        btnTankol1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        List_autok = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Autó GUI");
        setResizable(false);

        pnlUjAuto.setBorder(javax.swing.BorderFactory.createTitledBorder("Új autó"));

        Chk_beintitva.setText("beindítva");

        btnResetUezemaDefekt.setText("reset");
        btnResetUezemaDefekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetUezemaDefektActionPerformed(evt);
            }
        });

        btnGarazsba.setText("garázsba");
        btnGarazsba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGarazsbaActionPerformed(evt);
            }
        });

        jLabel2.setText("pótkerék:");

        Mum_potkerek.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4, 1));

        Chk_defekt.setText("Defekt");

        jLabel3.setText("Üzemanyag:");

        jLabel5.setText("Üzemanyagszint:");

        Mum_uzemanyagszint.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4, 1));

        jLabel6.setText("l");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setText("db");

        jLabel8.setText("Autó neve:");

        javax.swing.GroupLayout pnlUjAutoLayout = new javax.swing.GroupLayout(pnlUjAuto);
        pnlUjAuto.setLayout(pnlUjAutoLayout);
        pnlUjAutoLayout.setHorizontalGroup(
            pnlUjAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUjAutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUjAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUjAutoLayout.createSequentialGroup()
                        .addGroup(pnlUjAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Chk_defekt)
                            .addGroup(pnlUjAutoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnResetUezemaDefekt))
                            .addGroup(pnlUjAutoLayout.createSequentialGroup()
                                .addGroup(pnlUjAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(pnlUjAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlUjAutoLayout.createSequentialGroup()
                                        .addComponent(Mum_potkerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlUjAutoLayout.createSequentialGroup()
                                        .addComponent(Mum_uzemanyagszint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 2, Short.MAX_VALUE))
                    .addGroup(pnlUjAutoLayout.createSequentialGroup()
                        .addGroup(pnlUjAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUjAutoLayout.createSequentialGroup()
                                .addComponent(Chk_beintitva)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGarazsba)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlUjAutoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(Txt_autoneve)))
                        .addContainerGap())))
        );
        pnlUjAutoLayout.setVerticalGroup(
            pnlUjAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUjAutoLayout.createSequentialGroup()
                .addGroup(pnlUjAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUjAutoLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUjAutoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlUjAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Txt_autoneve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlUjAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnResetUezemaDefekt)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlUjAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Mum_uzemanyagszint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(pnlUjAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUjAutoLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUjAutoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlUjAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Mum_potkerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Chk_defekt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlUjAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chk_beintitva)
                    .addComponent(btnGarazsba))
                .addContainerGap())
        );

        pnlGarazs.setBorder(javax.swing.BorderFactory.createTitledBorder("Garázs"));

        cmbAutok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Autók ---" }));
        cmbAutok.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAutokItemStateChanged(evt);
            }
        });

        sldEsely.setValue(0);
        sldEsely.setEnabled(false);
        sldEsely.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sldEselyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sldEselyMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sldEselyMouseReleased(evt);
            }
        });

        jLabel4.setText("esély defektre:");

        chbDefekt.setText("lehet defekt");
        chbDefekt.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbDefektStateChanged(evt);
            }
        });
        chbDefekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbDefektActionPerformed(evt);
            }
        });

        btnMegy.setText("megy");
        btnMegy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegyActionPerformed(evt);
            }
        });

        btnTankol1.setText("tankol");
        btnTankol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTankol1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGarazsLayout = new javax.swing.GroupLayout(pnlGarazs);
        pnlGarazs.setLayout(pnlGarazsLayout);
        pnlGarazsLayout.setHorizontalGroup(
            pnlGarazsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGarazsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGarazsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbDefekt)
                    .addComponent(jLabel4)
                    .addComponent(cmbAutok, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlGarazsLayout.createSequentialGroup()
                        .addComponent(btnMegy, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(btnTankol1))
                    .addComponent(sldEsely, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlGarazsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMegy, btnTankol1});

        pnlGarazsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbAutok, sldEsely});

        pnlGarazsLayout.setVerticalGroup(
            pnlGarazsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGarazsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbAutok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sldEsely, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbDefekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlGarazsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMegy)
                    .addComponent(btnTankol1))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel1.setText("Kiválasztott autó állapota:");

        jScrollPane1.setViewportView(List_autok);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlUjAuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlGarazs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlGarazs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlUjAuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sldEselyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldEselyMouseEntered
        if(tombonbelul(autok, melyikauto)){
            autok[melyikauto].setDefektEsely((int)sldEsely.getValue());
        }
    }//GEN-LAST:event_sldEselyMouseEntered

    private void btnResetUezemaDefektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetUezemaDefektActionPerformed
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnResetUezemaDefektActionPerformed

    private void btnGarazsbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGarazsbaActionPerformed
        if(!Txt_autoneve.getText().equals("") && !bennevan(new String[]{"v"}/*cmbAutok.getComponents()*/, Txt_autoneve.getText())){
            cmbAutok.addItem(Txt_autoneve.getText());
            //cmbAutok.setSelectedIndex(1);
            Auto auto2 = new Auto(
                    Chk_beintitva.isSelected(), 
                    (int)Mum_uzemanyagszint.getValue(), 
                    Chk_defekt.isSelected(), 
                    (int)Mum_potkerek.getValue());
            auto2.addListener(this);
            autok = AuxiliaryFunctions.add(autok, auto2);
        }
    }//GEN-LAST:event_btnGarazsbaActionPerformed

    private void chbDefektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbDefektActionPerformed
        
    }//GEN-LAST:event_chbDefektActionPerformed

    private void sldEselyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldEselyMouseExited
        
    }//GEN-LAST:event_sldEselyMouseExited

    private void sldEselyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldEselyMouseReleased
        if(tombonbelul(autok, melyikauto)){
            autok[melyikauto].setDefektEsely((int)sldEsely.getValue());
            String s = "esély defektre:";
            s += (int)sldEsely.getValue() + "%";
            jLabel4.setText(s);
        }   
    }//GEN-LAST:event_sldEselyMouseReleased

    private void btnMegyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegyActionPerformed
        if(tombonbelul(autok, melyikauto)){
            autok[melyikauto].megy();
            //txaAllapot.setText("MEGY utáni állapot változás...");
        }
    }//GEN-LAST:event_btnMegyActionPerformed

    private void btnTankol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTankol1ActionPerformed
        if(tombonbelul(autok, melyikauto)){
            autok[melyikauto].tankol();
            //txaAllapot.setText("TANKOL utáni állapot változás...");
        }
    }//GEN-LAST:event_btnTankol1ActionPerformed

    private void chbDefektStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chbDefektStateChanged
        if(chbDefekt.isSelected()){
            if(tombonbelul(autok, melyikauto)){
                sldEsely.setEnabled(true);
                sldEsely.setValue(20);
                autok[melyikauto].setDefektEsely(sldEsely.getValue());
                String s = "esély defektre:";
                s += (int)sldEsely.getValue() + "%";
                jLabel4.setText(s);
            }
        }
        else{
            if(tombonbelul(autok, melyikauto)){
                sldEsely.setEnabled(false);
                sldEsely.setValue(0);
                autok[melyikauto].setDefektEsely(sldEsely.getValue());
                String s = "esély defektre:";
                s += (int)sldEsely.getValue() + "%";
                jLabel4.setText(s);
            }
        }
    }//GEN-LAST:event_chbDefektStateChanged

    private void cmbAutokItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAutokItemStateChanged
        melyikauto = cmbAutok.getSelectedIndex() -1;
        System.out.println(melyikauto);
        if(tombonbelul(autok, melyikauto)){
            itemsActive(true);
            actionValueChanged();
        }
        else{
            itemsActive(false);
            List_autok.removeAll();
        }
    }//GEN-LAST:event_cmbAutokItemStateChanged
    
    private <T> boolean tombonbelul(T[] tomb, int szam){
        return szam >= 0 && szam < tomb.length;
    }
    
    private <T> boolean bennevan(String[] tomb, String element){
        boolean both = tomb[0].equals(element);
        for (int i = 1; i < tomb.length && !both; i++) {
            both = tomb[i].equals(element);
        }
        return both;
    }
    
    private void itemsActive(boolean active){
        sldEsely.setEnabled(active);
        btnMegy.setEnabled(active);
        btnTankol1.setEnabled(active);
        chbDefekt.setEnabled(active);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiAutosProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiAutosProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiAutosProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiAutosProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiAutosProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Chk_beintitva;
    private javax.swing.JCheckBox Chk_defekt;
    private javax.swing.JList<String> List_autok;
    private javax.swing.JSpinner Mum_potkerek;
    private javax.swing.JSpinner Mum_uzemanyagszint;
    private javax.swing.JTextField Txt_autoneve;
    private javax.swing.JButton btnGarazsba;
    private javax.swing.JButton btnMegy;
    private javax.swing.JButton btnResetUezemaDefekt;
    private javax.swing.JButton btnTankol1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chbDefekt;
    private javax.swing.JComboBox<String> cmbAutok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlGarazs;
    private javax.swing.JPanel pnlUjAuto;
    private javax.swing.JSlider sldEsely;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionValueChanged() {
        if(tombonbelul(autok, melyikauto)){
            List_autok.removeAll();
            DefaultListModel demoList = new DefaultListModel();
            demoList.addElement((Object)"Motor: %s".formatted(autok[melyikauto].getMegye() ? "Megy." : "Nem megy."));
            demoList.addElement((Object)"Üzemanyagszint: %d".formatted(autok[melyikauto].getUzemanyag()));
            demoList.addElement((Object)"Pótkerekek száma: %d".formatted(autok[melyikauto].getPotkerekek()));
            demoList.addElement((Object)"Kerekek: %s".formatted(autok[melyikauto].getDefekt() ? "Defektesek." : "Nem defektesek."));
            demoList.addElement((Object)"Esély a defektre: %d".formatted(autok[melyikauto].getDefektEsely()));
            List_autok = new JList(demoList);
        }
    }
}
